<a href="https://colab.research.google.com/github/armandordorica/Advanced-Python/blob/master/coding_challenges/game_of_life.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
grid = [
  [0,1,0],
  [0,0,1],
  [1,1,1],
  [0,0,0]
]

In [2]:
import numpy as np

class Cell:
  def __init__(self, i, j, grid): 
    self.i = i
    self.j = j
    self.grid = grid
    self.num_neighbours = self.get_num_neighbours()
    self.neighbours_indices = self.get_neighbours_indices()
    self.current_status = grid[i][j]

    self.next_status = self.get_status()

  def get_neighbours_indices(self): 
    grid = np.array(self.grid)
    i = self.i
    j=self.j 
    i_s = [i-1, i, i+1]
    j_s = [j-1, j, j+1]

    cartesian_product = [(i,j) for i in i_s for j in j_s]

    cartesian_product.remove((i,j))
    possible_neighbours = cartesian_product
    max_rows = grid.shape[0]-1
    max_cols = grid.shape[1]-1
    filtered_possible_values = list(filter( lambda x: (x[0] >= 0 and x[0]<= max_rows) and (x[1]>=0 and x[1]<= max_cols), possible_neighbours))
    return filtered_possible_values

  def get_neighbours_values(self):
    return list(map(lambda x: self.grid[x[0]][x[1]], self.neighbours_indices))


  def get_num_neighbours(self): 
    self.neighbours_indices = self.get_neighbours_indices()
    self.neighbours_values = self.get_neighbours_values()
    return sum(self.neighbours_values)

  def get_status(self): 
    if self.current_status == 1: 
      if self.num_neighbours < 2 or self.num_neighbours > 3: 
        self.next_status = 0 

      if self.num_neighbours == 2 or self.num_neighbours ==3: 
        self.next_status = 1 

    elif self.current_status == 0:
      if self.num_neighbours == 3:
        self.next_status = 1 
      
      else: 
        self.next_status = self.current_status 
    
    return self.next_status

      
class Grid:
  def __init__(self, grid): 
    self.grid = grid 
    self.grid_of_cells = self.get_grid_of_cells()
    self.next_status_grid = self.get_next_status_grid()
    print("Grid at t:\n{}".format(np.array(self.grid)))
    print("Grid at t+1:\n{}".format(np.array(self.next_status_grid)))

  def get_grid_of_cells(self):
    self.grid_of_cells = []
    for i in range(0, len(self.grid)):
      row =  []
      for j in range(0, len(self.grid[i])):
        #print(i,j)
        cell = Cell(i, j, self.grid)
        row.append(cell)
      self.grid_of_cells.append(row)

    return self.grid_of_cells
  
  def get_next_status_grid(self): 
    self.next_status_grid  = []

    for i in range(0, len(self.grid_of_cells)): 
      row = []
      for j in range(0, len(self.grid_of_cells[i])):
        #print(i,j)
        #print(self.grid_of_cells[i][j].next_status)
        row.append(self.grid_of_cells[i][j].next_status)

      self.next_status_grid.append(row)
  
    return self.next_status_grid


In [3]:
grid = [
  [0,1,0],
  [0,0,1],
  [1,1,1],
  [0,0,0]
]

In [4]:
new_grid = Grid(grid)

Grid at t:
[[0 1 0]
 [0 0 1]
 [1 1 1]
 [0 0 0]]
Grid at t+1:
[[0 0 0]
 [1 0 1]
 [0 1 1]
 [0 1 0]]
