<a href="https://colab.research.google.com/github/armandordorica/Advanced-Python/blob/master/coding_challenges/rotting_oranges.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Instructions
In a given grid, each cell can have one of three values:

* the value 0 representing an empty cell;
* the value 1 representing a fresh orange;
* the value 2 representing a rotten orange.

Every minute, any fresh orange that is adjacent (4-directionally) to a rotten orange becomes rotten.

Return the minimum number of minutes that must elapse until no cell has a fresh orange.  If this is impossible, return -1 instead.



## Cell Class
* Each cell has location (i,j) in a grid and a grid. 
* Each cell lives in a Grid
* Each cell must be able to obtain the indices of the neighbours within the grid 
* Each cell must be able to obtain the values of the neighbours within the grid 
* Each cell must be able to obtain the number of rotten neighbours (based on their values)
* Each cell must be able to obtain its next status based on its current status and the number of rotten neighbours 

## Grid Class 
* Each Grid is initialized with a numpy array 
* A Grid can then be represented as an m x n array of Cell objects 
* A Grid has num_rows and num_cols based on the shape[0] and shape[1] of the numpy array it is initialized with
* A Grid has `num_ones` as attribute, which corresponds to the number of fresh oranges it still has. 
* A Grid must have a `next_grid` based on the next value of each of the cells given the neighbours within the Grid. 



In [3]:
class Cell:
  def __init__(self, i,j,grid): 
    self.i = i 
    self.j = j
    self.grid = np.array(grid)

    self.current_status = self.grid[self.i][self.j]

    self.neighbours_indices = self.get_neighbours_indices()

    self.num_rotten_neighbours = self.get_rotten_neighbours()
    self.next_status = self.get_next_status()


  def get_neighbours_indices(self): 
    possible_neighbours = [(self.i-1,self.j), (self.i, self.j-1), (self.i, self.j+1), (self.i+1,self.j)]

    max_rows = self.grid.shape[0]-1
    max_cols = self.grid.shape[1]-1

    filtered_neighbours = list(filter(lambda x: (x[0] >= 0 and x[0]<= max_rows) and (x[1]>=0 and x[1]<= max_cols), possible_neighbours))

    return filtered_neighbours

  def get_rotten_neighbours(self):
    rotten_neighbours = []
    for i in range(0, len(self.neighbours_indices)):
      neighbour_value = self.grid[self.neighbours_indices[i][0], self.neighbours_indices[i][1]]

      if neighbour_value == 2: 
        rotten_neighbours.append(self.neighbours_indices[i])
        #print(cell.grid[cell.neighbours_indices[i][0], cell.neighbours_indices[i][1]])


    return len(rotten_neighbours)


  def get_next_status(self): 
    if self.num_rotten_neighbours > 0 and self.current_status ==1: 
      self.next_status = 2 

    else: 
      self.next_status  = self.current_status
    
    return self.next_status


    # self.current_status = grid[i][j]

In [4]:
class Grid: 
  def __init__(self, grid): 
    self.grid = np.array(grid)
    self.num_rows = self.grid.shape[0]
    self.num_cols = self.grid.shape[1]
    self.grid_of_cells = self.get_grid_of_cells()

    self.next_grid = self.get_next_status_grid()

    self.num_ones = self.get_num_ones()


  
  def get_grid_of_cells(self): 
    self.grid_of_cells = []
    for i in range(0, self.num_rows):
      row = []
      for j in range(0, self.num_cols): 
        cell = Cell(i, j, self.grid)
        row.append(cell)
        #print(i, j, self.grid[i][j])
        
      self.grid_of_cells.append(row)
    
    return self.grid_of_cells


  def get_next_status_grid(self): 
    self.next_grid = []

    for i in range(0, self.num_rows):
      rows= []
      for j in range(0, self.num_cols):
        rows.append(self.grid_of_cells[i][j].next_status)
      
      self.next_grid.append(rows)

    
    
    return np.array(self.next_grid)

  def get_num_ones(self):
    unique, counts = np.unique(self.grid, return_counts=True)
    counts = dict(zip(unique, counts))

    if 1 in counts.keys(): 
      return counts[1]

    else: 
      return 0


In [53]:
def get_num_iterations_required(input_grid): 
    ## Initializing list of grids
  iters = []
  initial_grid = Grid(input_grid)
  iters.append(initial_grid)

  # initialize counter
  i = 0

  num_ones = []
  curr_num_ones = iters[i].num_ones
  num_ones.append(iters[i].num_ones)

  while curr_num_ones > 0: 
    iters.append(Grid(iters[i].next_grid))

    curr_num_ones = iters[i+1].num_ones
    num_ones.append(iters[i+1].num_ones)

    if i>0 and num_ones[i] == num_ones[i-1]: 
      break

    i+=1


  for i in range(0,len(iters)):
    print(iters[i].grid)

  if num_ones[-1]==0:
    return (len(iters)-1)

  if num_ones[-1]==1:
    return (-1)

  else: 
    print("Error")
    print("num_ones:{}".format(num_ones))

  

# Test Cases

In [65]:
g1 = [
  [2,1,1],
  [1,1,0],
  [0,1,1]
  ]
np.array(g1)

array([[2, 1, 1],
       [1, 1, 0],
       [0, 1, 1]])

In [66]:
get_num_iterations_required(g1)

[[2 1 1]
 [1 1 0]
 [0 1 1]]
[[2 2 1]
 [2 1 0]
 [0 1 1]]
[[2 2 2]
 [2 2 0]
 [0 1 1]]
[[2 2 2]
 [2 2 0]
 [0 2 1]]
[[2 2 2]
 [2 2 0]
 [0 2 2]]


4

In [67]:
g2 = [[2,1,1],[0,1,1],[1,0,1]]
np.array(g2)

array([[2, 1, 1],
       [0, 1, 1],
       [1, 0, 1]])

In [68]:
get_num_iterations_required(g2)

[[2 1 1]
 [0 1 1]
 [1 0 1]]
[[2 2 1]
 [0 1 1]
 [1 0 1]]
[[2 2 2]
 [0 2 1]
 [1 0 1]]
[[2 2 2]
 [0 2 2]
 [1 0 1]]
[[2 2 2]
 [0 2 2]
 [1 0 2]]
[[2 2 2]
 [0 2 2]
 [1 0 2]]
[[2 2 2]
 [0 2 2]
 [1 0 2]]


-1